---
kind: pipeline
name: "Push"

steps:
  - name: "Push to customer repo"
    image: node:10.11
    environment:
      GITHUB_API_KEY:
        from_secret: kite_bot_key
      GITHUB_CUSTOMER_NAME:
        from_secret: optimize_repo_name
    commands:
      - set -x
      - git config --global user.name "Kite Bot"
      - git config --global user.email "kite-bot@heliostech.fr"
      - git remote add authenticated-origin https://kite-bot:$GITHUB_API_KEY@github.com/${DRONE_REPO}
      - git remote add customer-repo https://kite-bot:$GITHUB_API_KEY@github.com/$GITHUB_CUSTOMER_NAME
      - git fetch authenticated-origin
      - git fetch customer-repo
      - git push -f customer-repo HEAD:master
    when:
      event:
        - push
      branch:
        - customer/optimize
